// Generated by tools/make_voices.py. Normalized bubble text -> [clip, seconds].
'use strict';
const VOICE_LINES = {
 "let s go jump hold tap to spin dash": [
  "assets/voice/sonic_let_s_go_jump_hold_tap_to_spin_dash.mp3",
  2.77
 ],
 "badnik jump then press again in the air to homing attack": [
  "assets/voice/sonic_badnik_jump_then_press_again_in_the_air_to_homing_atta.mp3",
  3.24
 ],
 "chain it tap again after every hit": [
  "assets/voice/sonic_chain_it_tap_again_after_every_hit.mp3",
  2.01
 ],
 "tip homing attacks chain through enemies in mid air": [
  "assets/voice/sonic_tip_homing_attacks_chain_through_enemies_in_mid_air.mp3",
  2.04
 ],
 "too easy": [
  "assets/voice/sonic_too_easy.mp3",
  0.57
 ],
 "way past cool": [
  "assets/voice/sonic_way_past_cool.mp3",
  0.94
 ],
 "next": [
  "assets/voice/sonic_next.mp3",
  0.5
 ],
 "keep em coming": [
  "assets/voice/sonic_keep_em_coming.mp3",
  0.84
 ],
 "too slow": [
  "assets/voice/sonic_too_slow.mp3",
  0.57
 ],
 "is that all": [
  "assets/voice/sonic_is_that_all.mp3",
  0.52
 ],
 "smooth": [
  "assets/voice/sonic_smooth.mp3",
  0.39
 ],
 "ho ho ho nice of you to drop by hedgehog": [
  "assets/voice/eggman_ho_ho_ho_nice_of_you_to_drop_by_hedgehog.mp3",
  3.47
 ],
 "jump and smack his ship or again mid air to home in": [
  "assets/voice/sonic_jump_and_smack_his_ship_or_again_mid_air_to_home_in.mp3",
  1.23
 ],
 "ho ho ho you think that was my best": [
  "assets/voice/eggman_ho_ho_ho_you_think_that_was_my_best.mp3",
  2.8
 ],
 "behold the egg colossus": [
  "assets/voice/eggman_behold_the_egg_colossus.mp3",
  2.12
 ],
 "fuck": [
  "assets/voice/sonic_fuck.mp3",
  0.63
 ],
 "language hedgehog": [
  "assets/voice/eggman_language_hedgehog.mp3",
  1.7
 ],
 "okay time to go super": [
  "assets/voice/sonic_okay_time_to_go_super.mp3",
  1.36
 ],
 "let s do this mash for light fists hold for a laser": [
  "assets/voice/sonic_let_s_do_this_mash_for_light_fists_hold_for_a_laser.mp3",
  2.95
 ],
 "beat a part till it sparks then rip it off and throw it back": [
  "assets/voice/sonic_beat_a_part_till_it_sparks_then_rip_it_off_and_throw_i.mp3",
  2.95
 ],
 "let s double up light clones": [
  "assets/voice/sonic_let_s_double_up_light_clones.mp3",
  1.75
 ],
 "burning out i need rings grab the gold ones": [
  "assets/voice/sonic_burning_out_i_need_rings_grab_the_gold_ones.mp3",
  1.36
 ],
 "his core s exposed hit it with everything": [
  "assets/voice/sonic_his_core_s_exposed_hit_it_with_everything.mp3",
  2.12
 ],
 "no no my masterpiece": [
  "assets/voice/eggman_no_no_my_masterpiece.mp3",
  2.77
 ],
 "no my power": [
  "assets/voice/sonic_no_my_power.mp3",
  0.91
 ],
 "i ll get you next time sonic": [
  "assets/voice/eggman_i_ll_get_you_next_time_sonic.mp3",
  2.17
 ],
 "too slow eggman": [
  "assets/voice/sonic_too_slow_eggman.mp3",
  1.18
 ],
 "mash": [
  "assets/voice/sonic_mash.mp3",
  0.42
 ],
 "impossible": [
  "assets/voice/eggman_impossible.mp3",
  1.02
 ],
 "ugh gotta mash harder": [
  "assets/voice/sonic_ugh_gotta_mash_harder.mp3",
  0.99
 ],
 "catch egghead to throw it": [
  "assets/voice/sonic_catch_egghead_to_throw_it.mp3",
  0.94
 ],
 "my beautiful robot": [
  "assets/voice/eggman_my_beautiful_robot.mp3",
  1.67
 ],
 "big fist incoming fly out of the way": [
  "assets/voice/sonic_big_fist_incoming_fly_out_of_the_way.mp3",
  2.4
 ],
 "fist again dodge it": [
  "assets/voice/sonic_fist_again_dodge_it.mp3",
  1.12
 ],
 "he s gonna slam stay up high": [
  "assets/voice/sonic_he_s_gonna_slam_stay_up_high.mp3",
  1.72
 ],
 "shit i better smash those rockets": [
  "assets/voice/sonic_shit_i_better_smash_those_rockets.mp3",
  1.91
 ],
 "more rockets em": [
  "assets/voice/sonic_more_rockets_em.mp3",
  1.49
 ],
 "laser huh two can play that game hold aim at his face": [
  "assets/voice/sonic_laser_huh_two_can_play_that_game_hold_aim_at_his_face.mp3",
  1.72
 ],
 "beam him back hold": [
  "assets/voice/sonic_beam_him_back_hold.mp3",
  0.65
 ],
 "heads up falling debris": [
  "assets/voice/sonic_heads_up_falling_debris.mp3",
  1.33
 ],
 "that arm s loose time to rip it off fly close hold": [
  "assets/voice/sonic_that_arm_s_loose_time_to_rip_it_off_fly_close_hold.mp3",
  1.7
 ],
 "that rocket pod s loose time to rip it off fly close hold": [
  "assets/voice/sonic_that_rocket_pod_s_loose_time_to_rip_it_off_fly_close_h.mp3",
  2.06
 ],
 "that chest plate s loose time to rip it off fly close hold": [
  "assets/voice/sonic_that_chest_plate_s_loose_time_to_rip_it_off_fly_close_.mp3",
  2.25
 ]
};
