#!/usr/bin/env python3
"""Pack models_tornado.json (from export_tornado.js) + textures into js/models_tornado.js."""
import json, base64, io, os
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.environ.get('WORK', '/tmp/conv')
OUT = os.path.join(HERE, '..', '..', 'js', 'models_tornado.js')
m = json.load(open(os.path.join(WORK, 'models_tornado.json')))
# ColladaLoader leaves joints without a sid unnamed (Tails' Neck); take the name from the DAE, in document order
import re
dae = open(os.path.join(WORK, 'tails.dae')).read()
dae_names = re.findall(r'<node[^>]*?name="([^"]+)"', dae[dae.find('<library_visual_scenes'):])
for i, n in enumerate(m['tails']['nodes']):
    if not n['n']: n['n'] = dae_names[i]
tex = {}
for t in m['tails']['textures']:
    im = Image.open(os.path.join(WORK, 'images', t)).convert('RGB')
    if max(im.size) > 512: im = im.resize((im.width // 2, im.height // 2), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'JPEG', quality=86)
    tex[t] = 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode()
for t in m['tornado']['textures']:
    raw = open(os.path.join(WORK, 'ttex', t), 'rb').read()
    tex[t] = 'data:image/png;base64,' + base64.b64encode(raw).decode()
m['tex'] = tex
src = ("// Tails (Sonic Generations model, ripped by Random Talking Bush for The Models Resource) with Generations\n"
       "// clips, and the Tornado from Sonic Adventure DX (ripped by josh98), both from the Unity project\n"
       "// JonathanOdgis/Sonic-The-Hedgehog-Controller-Unity. Generated by tools/convert_models/pack_tornado.py.\n"
       "// Fan use only; the characters belong to SEGA.\n"
       "'use strict';\nconst TOR_MODELS = " + json.dumps(m, separators=(',', ':')) + ";\n")
open(OUT, 'w').write(src)
print('wrote', OUT, len(src) // 1024, 'KB')
