#!/usr/bin/env python3
"""Pack models.json (from export.js) + textures into js/models3d.js."""
import json, base64, io, os
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.environ.get('WORK', '/tmp/conv')
OUT = os.path.join(HERE, '..', '..', 'js', 'models3d.js')
m = json.load(open(os.path.join(WORK, 'models.json')))
tex = {}
for k in ('sonic', 'pawn'):
    for t in m[k]['textures']:
        im = Image.open(os.path.join(WORK, 'images', t)).convert('RGB')
        b = io.BytesIO()
        if 'eye_ems' in t:
            im.save(b, 'PNG', optimize=True); uri = 'data:image/png;base64,'
        else:
            im.save(b, 'JPEG', quality=88); uri = 'data:image/jpeg;base64,'
        tex[t] = uri + base64.b64encode(b.getvalue()).decode()
m['tex'] = tex
src = ("// Sonic (Sonic Generations model, ripped by Apoc Hedgie for The Models Resource) and an Egg Pawn,\n"
       "// with Generations animations converted from the Unity project JonathanOdgis/Sonic-The-Hedgehog-Controller-Unity.\n"
       "// Generated by tools/convert_models (see its README). Fan use only; the characters belong to SEGA.\n"
       "'use strict';\nconst ESC_MODELS = " + json.dumps(m, separators=(',', ':')) + ";\n")
open(OUT, 'w').write(src)
print('wrote', OUT, len(src) // 1024, 'KB')
